### ISSUE TITLE
Add name before /me on mattermost

### ISSUE THREAD

**Issue by Yoz0** [Sindarus/slack_irc_bot_python#16]
When a user input `/me like github` in Matter most it shows as : 
_like github_
It should be : 
**User** _like github_

**Comment by Sindarus** [comment]
Your issue is ambiguous because it lacks ponctuation. Is it "when a user inputs `/me likes github` [on IRC], in mattermost it shows as :"
or is it "When a user inputs `/me likes github`  in Mattermost, it shows [on IRC] as :"

**Comment by Sindarus** [comment]
Let's say the first interpretation is the right one, because the other one would mean your observations were wrong.
This issue is invalid, because it _should_ appear like : _likes github_ on mattermost, because this is the behaviour when you type `/me likes github` directly in mattermost.

**Comment by Yoz0** [comment]
The first interpretation is correct, sorry for the ambiguation.

Mattermost is stupid ! IMHO the bot should follow irc logic.

**Comment by Sindarus** [comment]
Yeah
